# -*- coding: utf-8 -*-
# cocos2dx格式lua转换成cocos2dx格式js
# 常量模块
# by 丁豪 2020-03-20

TokenLua = {
    "TokenCommentAll"          : "--[[",
    "TokenCommentAllEnd"       : "]]",
    "TokenCommentLine"         : "--",
    "TokenAnd"                 : "and",
    "TokenDo"                  : "do",
    "TokenElse"                : "else",
    "TokenElseif"              : "elseif",
    "TokenEnd"                 : "end",
    "TokenFalse"               : "false",
    "TokenIf"                  : "if",
    "TokenLocal"               : "local",
    "TokenNil"                 : "nil",
    "TokenNot"                 : "not",
    "TokenOr"                  : "or",
    "TokenThen"                : "then",
    "TokenTrue"                : "true",
    "TokenWhile"               : "while",
    "TokenFor"                 : "for",
    "TokenBreak"               : "break",
    "TokenContinue"            : "continue",
    "TokenFunction"            : "function",
    "TokenReturn"              : "return",
    "TokenIn"                  : "in",
    # "TokenID"                  : "<id>",
    # "TokenString"              : "<string>",
    # "TokenNumber"              : "<number>",
    "TokenAdd"                 : "+",
    "TokenSub"                 : "-",
    "TokenMul"                 : "*",
    "TokenDiv"                 : "/",
    "TokenPercent"             : "%",
    # "TokenLen"                 : "#",
    "TokenLeftParen"           : "(",
    "TokenRightParen"          : ")",
    "TokenLeftSquare"          : "[",
    "TokenRightSquare"         : "]",
    "TokenLeftBrace"           : "{",
    "TokenRightBrace"          : "}",
    "TokenAssign"              : "=",
    "TokenColon"               : ":",
    "TokenSemicolon"           : ";",
    "TokenComma"               : ",",
    "TokenEqual"               : "==",
    "TokenNotEqual"            : "~=",
    "TokenLess"                : "<",
    "TokenLessEqual"           : "<=",
    "TokenGreater"             : ">",
    "TokenGreaterEqual"        : ">=",
    "TokenDot"                 : ".",
    "TokenDanYin"              : "'",
    "TokenShuangYin"           : "\"",
    "TokenConcat"              : "..",
    "TokenConcat1"             : "...",
    "TokenEOF"                 : "<eof>"
}

TokenJs = {
    "TokenCommentAll"          : "/*",
    "TokenCommentAllEnd"       : "*/",
    "TokenCommentLine"         : "//",
    "TokenAnd"                 : "&&",
    "TokenDo"                  : "){",
    "TokenElse"                : "}else{",
    "TokenElseif"              : "}else if (",
    "TokenEnd"                 : "}",
    "TokenFalse"               : "false",
    "TokenIf"                  : "if (",
    "TokenLocal"               : "let",
    "TokenNil"                 : "null",
    "TokenNot"                 : "!",
    "TokenOr"                  : "||",
    "TokenThen"                : "){",
    "TokenTrue"                : "true",
    "TokenWhile"               : "while (",
    "TokenFor"                 : "for (",
    "TokenBreak"               : "break",
    "TokenContinue"            : "continue",
    "TokenFunction"            : "function",
    "TokenReturn"              : "return",
    "TokenIn"                  : "in",
    # "TokenID"                  : "<id>",
    # "TokenString"              : "<string>",
    # "TokenNumber"              : "<number>",
    "TokenAdd"                 : "+",
    "TokenSub"                 : "-",
    "TokenMul"                 : "*",
    "TokenDiv"                 : "/",
    "TokenPercent"             : "%",
    # "TokenLen"                 : "#",
    "TokenLeftParen"           : "(",
    "TokenRightParen"          : ")",
    "TokenLeftSquare"          : "[",
    "TokenRightSquare"         : "]",
    "TokenLeftBrace"           : "{",
    "TokenRightBrace"          : "}",
    "TokenAssign"              : "=",
    "TokenColon"               : ":",
    "TokenSemicolon"           : ";",
    "TokenComma"               : ",",
    "TokenEqual"               : "==",
    "TokenNotEqual"            : "!=",
    "TokenLess"                : "<",
    "TokenLessEqual"           : "<=",
    "TokenGreater"             : ">",
    "TokenGreaterEqual"        : ">=",
    "TokenDot"                 : ".",
    "TokenDanYin"              : "'",
    "TokenShuangYin"           : "\"",
    "TokenConcat"              : "+",
    "TokenConcat1"             : "...",
    "TokenEOF"                 : "<eof>"
}